const languageTranslations = {
    english: {
        hello: "Hello",
        thank_you: "Thank you",
        please: "Please",
        goodbye: "Goodbye",
        yes: "Yes",
        no: "No",
        excuse_me: "Excuse me",
        sorry: "Sorry",
        help: "Help",
        good_morning: "Good Morning",
        good_night: "Good Night",
        how_are_you: "How are you?",
        what_is_your_name: "What is your name?",
        nice_to_meet_you: "Nice to meet you",
        where_is_the_bathroom: "Where is the bathroom?",
        can_you_help_me: "Can you help me?",
        i_love_you: "I love you",
        how_much: "How much?",
        what_time_is_it: "What time is it?",
        where: "Where?",
        when: "When?",
        why: "Why?",
        who: "Who?",
        what: "What?",
        which: "Which?",
        can: "Can?",
        will: "Will?"
    },
    turkish: {
        hello: "Merhaba",
        thank_you: "Teşekkür ederim",
        please: "Lütfen",
        goodbye: "Hoşça kal",
        yes: "Evet",
        no: "Hayır",
        excuse_me: "Affedersiniz",
        sorry: "Üzgünüm",
        help: "Yardım",
        good_morning: "Günaydın",
        good_night: "İyi geceler",
        how_are_you: "Nasılsınız?",
        what_is_your_name: "Adınız nedir?",
        nice_to_meet_you: "Tanıştığımıza memnun oldum",
        where_is_the_bathroom: "Tuvalet nerede?",
        can_you_help_me: "Bana yardım edebilir misiniz?",
        i_love_you: "Seni seviyorum",
        how_much: "Bu ne kadar?",
        what_time_is_it: "Saat kaç?",
        where: "Nerede?",
        when: "Ne zaman?",
        why: "Neden?",
        who: "Kim?",
        what: "Ne?",
        which: "Hangisi?",
        can: "Yapabilir miyim?",
        will: "Gidecek miyim?"
    },
    korean: {
        hello: "안녕하세요 (Annyeonghaseyo)",
        thank_you: "감사합니다 (Gamsahamnida)",
        please: "부탁합니다 (Butakhamnida)",
        goodbye: "안녕히 가세요 (Annyeonghi gaseyo)",
        yes: "네 (Ne)",
        no: "아니요 (Aniyo)",
        excuse_me: "죄송합니다 (Joesonghamnida)",
        sorry: "죄송합니다 (Joesonghamnida)",
        help: "도와주세요 (Dowajuseyo)",
        good_morning: "좋은 아침입니다 (Joeun achimimnida)",
        good_night: "안녕히 주무세요 (Annyeonghi jumuseyo)",
        how_are_you: "어떻게 지내세요? (Eotteohge jinaeseyo?)",
        what_is_your_name: "이름이 뭐예요? (Ireumi mwoyeyo?)",
        nice_to_meet_you: "만나서 반가워요 (Mannaseo bangawoyo)",
        where_is_the_bathroom: "화장실 어디예요? (Hwajangsil eodi-yeyo?)",
        can_you_help_me: "도와주실 수 있나요? (Dowajusil su innayo?)",
        i_love_you: "사랑해요 (Salanghaeyo)",
        how_much: "얼마예요? (Eolmayeyo?)",
        what_time_is_it: "지금 몇 시예요? (Jigeum myeot siyeyo?)",
        where: "어디예요? (Eodieyo?)",
        when: "언제예요? (Eonje-yeyo?)",
        why: "왜요? (Waeyo?)",
        who: "누구예요? (Nuguyeyo?)",
        what: "무엇이에요? (Mueos-ieyo?)",
        which: "어느 것이에요? (Eoneu geos-ieyo?)",
        can: "할 수 있어요? (Hal su isseoyo?)",
        will: "갈까요? (Galkkayo?)"
    },
    srilankan: {
        hello: "හෙලෝ (Helō)",
        thank_you: "ස්තුතියි (Sthutiyi)",
        please: "කරුණාකර (Karunākar)",
        goodbye: "සමුගන්නවා (Samugannavā)",
        yes: "ඔව් (Ov)",
        no: "නැහැ (Næhæ)",
        excuse_me: "කණගාටුයි (Kaṇagāṭuyi)",
        sorry: "කණගාටුයි (Kaṇagāṭuyi)",
        help: "ආධාරය (Ādhāraya)",
        good_morning: "සුභ උදෑසනක් (Subha udǣsanak)",
        good_night: "සුභ රෑක් (Subha rǣk)",
        how_are_you: "ඔබට කෙසේද? (Obaṭa kesēda?)",
        what_is_your_name: "ඔබගේ නම මොකක්ද? (Obagē nama mokakda?)",
        nice_to_meet_you: "ඔබට හමුවීමට සතුටුයි (Obaṭa hamuvīmaṭa sathutuyi)",
        where_is_the_bathroom: "මිනිස්හල කුඩා කාමරය කොහේද? (Miniṣhala kuḍā kāmaraya kohēda?)",
        can_you_help_me: "මට උදව් කරන්නේද? (Maṭa udav karannēda?)",
        i_love_you: "මට ඔබට ආදරෙයි (Maṭa obata ādarēyi)",
        how_much: "මෙය කොච්චරද? (Meya kochchara da?)",
        what_time_is_it: "මෙන්න කාලය කුමක්ද? (Menna kālaya kumakda?)",
        where: "කොහේ? (Kohē?)",
        when: "කොහෙද? (Koheda?)",
        why: "කෙසේද? (Kesēda?)",
        who: "කව්ද? (Kawda?)",
        what: "මොකක්ද? (Mokakda?)",
        which: "කොමක්ද? (Komaḳda?)",
        can: "හැකද? (Hækadā?)",
    },
    chinese: {
        hello: "你好 (Nǐ hǎo)",
        thank_you: "谢谢 (Xièxiè)",
        please: "请 (Qǐng)",
        goodbye: "再见 (Zàijiàn)",
        yes: "是的 (Shì de)",
        no: "不是 (Bù shì)",
        excuse_me: "对不起 (Duìbùqǐ)",
        sorry: "抱歉 (Bàoqiàn)",
        help: "帮助 (Bāngzhù)",
        good_morning: "早上好 (Zǎoshang hǎo)",
        good_night: "晚安 (Wǎn'ān)",
        how_are_you: "你好吗？ (Nǐ hǎo ma?)",
        what_is_your_name: "你叫什么名字？ (Nǐ jiào shénme míngzì?)",
        nice_to_meet_you: "很高兴见到你 (Hěn gāoxìng jiàn dào nǐ)",
        where_is_the_bathroom: "洗手间在哪里？ (Xǐshǒujiān zài nǎlǐ?)",
        can_you_help_me: "你能帮我吗？ (Nǐ néng bāng wǒ ma?)",
        i_love_you: "我爱你 (Wǒ ài nǐ)",
        how_much: "多少钱？ (Duōshǎo qián?)",
        what_time_is_it: "现在几点？ (Xiànzài jǐ diǎn?)",
        where: "哪里？ (Nǎlǐ?)",
        when: "什么时候？ (Shénme shíhòu?)",
        why: "为什么？ (Wèishénme?)",
        who: "谁？ (Shéi?)",
        what: "什么？ (Shénme?)",
        which: "哪个？ (Nǎge?)",
        can: "可以吗？ (Kěyǐ ma?)",
        will: "会吗？ (Huì ma?)"
    },
    hindi: {
        hello: "नमस्ते (Namaste)",
        thank_you: "धन्यवाद (Dhanyavād)",
        please: "कृपया (Kripayā)",
        goodbye: "अलविदा (Alvida)",
        yes: "हाँ (Hā̃)",
        no: "नहीं (Nahin)",
        excuse_me: "मुझे माफ करें (Mujhe māf karen)",
        sorry: "मुझे खेद है (Mujhe khed hai)",
        help: "मदद (Madad)",
        good_morning: "सुप्रभात (Suprabhāt)",
        good_night: "शुभ रात्रि (Shubh rātri)",
        how_are_you: "आप कैसे हैं? (Āp kaise hain?)",
        what_is_your_name: "आपका नाम क्या है? (Āpkā nām kyā hai?)",
        nice_to_meet_you: "आपसे मिलकर अच्छा लगा (Āpse milkar acchā lagā)",
        where_is_the_bathroom: "बाथरूम कहाँ है? (Bāthrūm kahā̃ hai?)",
        can_you_help_me: "क्या आप मेरी मदद कर सकते हैं? (Kyā āp merī madad kar sakte hain?)",
        i_love_you: "मैं तुमसे प्यार करता हूँ (Main tumse pyār kartā hūn)",
        how_much: "यह कितने का है? (Yah kitne kā hai?)",
        what_time_is_it: "अब क्या समय है? (Ab kyā samay hai?)",
        where: "कहाँ? (Kahā̃?)",
        when: "कब? (Kab?)",
        why: "क्यों? (Kyon?)",
        who: "कौन? (Kaun?)",
        what: "क्या? (Kyā?)",
        which: "कौन सा? (Kaun sā?)",
        can: "क्या कर सकता हूँ? (Kyā kar sakta hūn?)",
        will: "क्या होगा? (Kyā hogā?)"
    },
    norwegian: {
        hello: "Hallo",
        thank_you: "Takk",
        please: "Vær så snill",
        goodbye: "Ha det",
        yes: "Ja",
        no: "Nei",
        excuse_me: "Unnskyld meg",
        sorry: "Beklager",
        help: "Hjelp",
        good_morning: "God morgen",
        good_night: "God natt",
        how_are_you: "Hvordan har du det?",
        what_is_your_name: "Hva heter du?",
        nice_to_meet_you: "Hyggelig å møte deg",
        where_is_the_bathroom: "Hvor er toalettet?",
        can_you_help_me: "Kan du hjelpe meg?",
        i_love_you: "Jeg elsker deg",
        how_much: "Hvor mye koster det?",
        what_time_is_it: "Hva er klokka?",
        where: "Hvor?",
        when: "Når?",
        why: "Hvorfor?",
        who: "Hvem?",
        what: "Hva?",
        which: "Hvilken?",
        can: "Kan?",
        will: "Vil?"
    },
    french: {
        hello: "Bonjour",
        thank_you: "Merci",
        please: "S'il vous plaît",
        goodbye: "Au revoir",
        yes: "Oui",
        no: "Non",
        excuse_me: "Excusez-moi",
        sorry: "Désolé",
        help: "Aidez-moi",
        good_morning: "Bonjour",
        good_night: "Bonne nuit",
        how_are_you: "Comment ça va?",
        what_is_your_name: "Comment vous appelez-vous?",
        nice_to_meet_you: "Enchanté de vous rencontrer",
        where_is_the_bathroom: "Où sont les toilettes?",
        can_you_help_me: "Pouvez-vous m'aider?",
        i_love_you: "Je t'aime",
        how_much: "Combien ça coûte?",
        what_time_is_it: "Quelle heure est-il?",
        where: "Où?",
        when: "Quand?",
        why: "Pourquoi?",
        who: "Qui?",
        what: "Quoi?",
        which: "Lequel?",
        can: "Peut?",
        will: "Sera?"
    },
    spanish: {
        hello: "Hola",
        thank_you: "Gracias",
        please: "Por favor",
        goodbye: "Adiós",
        yes: "Sí",
        no: "No",
        excuse_me: "Perdón",
        sorry: "Lo siento",
        help: "Ayuda",
        good_morning: "Buenos días",
        good_night: "Buenas noches",
        how_are_you: "¿Cómo estás?",
        what_is_your_name: "¿Cuál es tu nombre?",
        nice_to_meet_you: "Encantado de conocerte",
        where_is_the_bathroom: "¿Dónde está el baño?",
        can_you_help_me: "¿Puedes ayudarme?",
        i_love_you: "Te quiero",
        how_much: "¿Cuánto cuesta?",
        what_time_is_it: "¿Qué hora es?",
        where: "¿Dónde?",
        when: "¿Cuándo?",
        why: "¿Por qué?",
        who: "¿Quién?",
        what: "¿Qué?",
        which: "¿Cuál?",
        can: "¿Puedo?",
        will: "¿Iré?"
    },
    italian: {
        hello: "Ciao",
        thank_you: "Grazie",
        please: "Per favore",
        goodbye: "Addio",
        yes: "Sì",
        no: "No",
        excuse_me: "Mi scusi",
        sorry: "Mi dispiace",
        help: "Aiuto",
        good_morning: "Buongiorno",
        good_night: "Buonanotte",
        how_are_you: "Come stai?",
        what_is_your_name: "Come ti chiami?",
        nice_to_meet_you: "Piacere di conoscerti",
        where_is_the_bathroom: "Dove si trova il bagno?",
        can_you_help_me: "Puoi aiutarmi?",
        i_love_you: "Ti amo",
        how_much: "Quanto costa?",
        what_time_is_it: "Che ora è?",
        where: "Dove?",
        when: "Quando?",
        why: "Perché?",
        who: "Chi?",
        what: "Cosa?",
        which: "Quale?",
        can: "Posso?",
        will: "Andrò?"
    }
};

// Handle the submit button click event
document.getElementById('submit-button').addEventListener('click', function() {
    const inputLanguage = document.getElementById('input-language').value;
    const outputLanguage = document.getElementById('output-language').value;

    const translationContainer = document.getElementById('translations');
    translationContainer.innerHTML = ''; // Clear previous translations

    // Check if the selected input and output languages exist in the translation data
    const inputTranslations = languageTranslations[inputLanguage];
    const outputTranslations = languageTranslations[outputLanguage];

    if (inputTranslations && outputTranslations) {
        for (const phrase in inputTranslations) {
            // Create a div for each translation
            const phraseDiv = document.createElement('div');
            phraseDiv.innerHTML = `<strong>${phrase}:</strong> ${inputTranslations[phrase]} -> ${outputTranslations[phrase]}`;
            translationContainer.appendChild(phraseDiv);
        }
    } else {
        translationContainer.innerHTML = 'One or both languages not found.';
    }
});


